Milestone 3: Game logic
Davidosky007/Tic-tac-toe-game pull request #4
Opened 2020-11-20 13:46 UTC by Davidosky007

## Tic Tac Toe Game Milestone 3: Game logic
In this milestone i
* added the different files responsible for the game logic
* grouped the different methods and class responsible for game functions 
* followed the DRY rule throughout.

2020-11-20 14:30 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @dipbazz & @dibdas**

Great job with the project so far, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] There are supposed to be no puts or gets outside of the main.rb file, please make the changes that your main file has the logic to run game and you lib files have the methods to store and save the logic.

- [ ] when the game begins it says press any key to "restart" the game. it should say start

- [ ] when a player enters an invalid position, the game should display a warning. right now the game goes on an infinite loop when I enter a letter or any number that's not from 1-9.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2020-11-20 22:59 UTC, ElijahTobs requested changes
# Status: Changes Required :recycle: 

## Hi @Davidosky007 

You've worked hard on this project but there's still a little more to be done before this milestone can be approved.

## [REQUIRED]

- [ ] There should be no `puts/print` and `gets.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] Your game asked me to enter any key but I entered several keys yet the game did not start. I had to press the `enter` key to start the game. Fix that.
- [ ] Your game allows the second player to select the position already selected by the first player.
![image](https://user-images.githubusercontent.com/16058470/99857591-d477c680-2b8b-11eb-9e09-e5a20e421c32.png)
- [ ] When the game is a draw, your game outputs **The game is over! try again you might be lucky next time**. Your game should mention to the players that it's a **draw*.*

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2020-11-21 08:01 UTC, mcrd25 approved these changes
# Changes Approved ✔️ 

Hi @Davidosky007 👋 

You have a few quirks but you have done a good job and meet the requirements.

Before you merge however please remove the commented out line in your Gemfile.
Please also consider the OPTIONAL comments below.

- As mentioned before only when a person presses enter the game starts so you should change the instructions. Same for quitting.

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email, or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-11-21 08:01 UTC, mcrd25 commented on bin/main.rb
> +  def display_board(board)
[OPTIONAL]
Your main.rb file has a lot of methods, Ideally, your executable script has little to no methods. 
Instead, your methods within your classes should be written in such a way that it returns values. In this case, having a method that returns the board to print.
Consider this for other methods in this file.

2020-11-21 08:01 UTC, mcrd25 commented on lib/board.rb
> +  attr_accessor :board
[OPTIONAL]
Using  a 'getter' method is a good way to avoid use of `attr_accessor`

2020-11-21 08:34 UTC, merged